name = "Video Pro"
license = "MIT"
licenselink = "https://github.com/e346m/thoth.git"
description = "CMS them for video"
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.36"

[author]
  name = "thoth"
  homepage = ""

